- name: Install Docker
  ansible.builtin.import_role:
    name: geerlingguy.docker
  become: true

- name: Add current user to docker group ({{ ansible_user }})
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true
  become: true

- name: Restart connection make sure group changes are applied
  ansible.builtin.meta: reset_connection

- name: Install Docker SDK for Python
  ansible.builtin.apt:
    name: python3-docker
    state: present
    install_recommends: false
  become: true
