server:
  vars:
    ansible_user: judgeadmin
    ansible_ssh_extra_args: -o StrictHostKeyChecking=no

  hosts:
    server-001:
      ansible_host: 192.168.101.172

    server-002:
      ansible_host: 192.168.101.192

    server-003:
      ansible_host: 192.168.101.33

    server-004:
      ansible_host: 192.168.101.136

    server-005:
      ansible_host: 192.168.101.254

# Groups by services

reverse-proxy:
  hosts:
    server-001:

domserver:
  hosts:
    server-001:

judgehost:
  hosts:
    server-002:
    server-003:
    server-004:
    server-005:
