server:
  vars:
    ansible_user: judgeadmin
    ansible_ssh_extra_args: -o StrictHostKeyChecking=no
    ansible_python_interpreter: /usr/bin/python3

  hosts:
    server001:
      ansible_host: 192.168.101.11

    server002:
      ansible_host: 192.168.101.20

    server003:
      ansible_host: 192.168.101.21

    server005:
      ansible_host: 192.168.101.22

# Groups by services

reverse_proxy:
  hosts:
    server001:

domserver:
  hosts:
    server001:

judgehost:
  hosts:
    server002:
    server003:
    server005:
