# Run: ansible-playbook playbooks/setup_no_password_login.yml -l 'server' --ask-pass --ask-become-pass
# If you have a different ssh key file, you can specify it with `-e ssh_public_key_file=/path/to/your/ssh/key.pub`

- name: Setup no password login
  hosts:
    - all

  vars:
    ssh_public_key_file: ~/.ssh/id_rsa.pub

  tasks:
    - name: Allow no password sudo for {{ ansible_user }}
      ansible.builtin.copy:
        dest: /etc/sudoers.d/ansible
        mode: "0440"
        content: "{{ ansible_user }}\tALL=(ALL:ALL) NOPASSWD:ALL"
      become: true

    - name: Set authorized key ({{ ssh_public_key_file }})
      ansible.posix.authorized_key:
        user: "{{ ansible_user }}"
        key: "{{ lookup('file', '{{ ssh_public_key_file }}') }}"

    - name: Disable SSH password login
      ansible.builtin.copy:
        dest: /etc/ssh/sshd_config.d/10-ansible.conf
        mode: "0644"
        content: PasswordAuthentication no
      notify: Restart ssh service
      become: true

  handlers:
    - name: Restart ssh service
      ansible.builtin.systemd:
        name: ssh
        state: restarted
      become: true
